In [218]:
import pandas as pd

In [219]:
data = pd.read_csv("all_kindle_review.csv")

In [220]:
data.head()
df = data[['reviewText','rating']]

In [221]:
df.shape

(12000, 2)

In [222]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [223]:
df['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [224]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [225]:
## quite balanced dataset

In [226]:
## Reiview with <3 rating is negative and >3 is postive sentiment reviw

In [227]:
df['rating'] = df['rating'].apply(lambda x:  0 if x < 3 else 1)

C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\2807906100.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].apply(lambda x:  0 if x < 3 else 1)


In [228]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [229]:
## lower all cases
df['reviewText'] =  df['reviewText'].str.lower()

C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\901655006.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] =  df['reviewText'].str.lower()


In [230]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [231]:
import nltk
from nltk.corpus import stopwords 
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\thaku\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [232]:
from bs4 import BeautifulSoup
import re
import lxml

In [233]:
## clean data 
# rem to make space in between a-z A-Z and 1- 9 otherwise words in the output come out without space too
df['reviewText'] = df['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 1-9]+' , ' ', x))
# stop words
df['reviewText'] = df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words("english")]))
# url removall
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))                                       


C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\310347748.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 1-9]+' , ' ', x))
C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\310347748.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words("english")]))
C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\310347748.py:8: SettingWith

In [234]:
# ## removing html tag         
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

#remove additional spaces
df['reviewText'] = df['reviewText'].apply(lambda x:" ".join(x.split()))

C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\2244317600.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\2244317600.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:" ".join(x.split()))


In [235]:
## Lemmatizer

In [236]:
from nltk.stem import WordNetLemmatizer

In [237]:
lemm = WordNetLemmatizer()

In [238]:
def lemm_text(sent):
    return " ".join([lemm.lemmatize(x) for x in sent.split()])

In [239]:
df['reviewText'] = df['reviewText'].apply(lambda x:lemm_text(x))

C:\Users\thaku\AppData\Local\Temp\ipykernel_15284\1183251349.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:lemm_text(x))


In [240]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],
                                              test_size=0.20)

In [241]:
#bow
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [242]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [243]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [244]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [245]:
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [246]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.5725


In [247]:
confusion_matrix(y_test,y_pred_tfidf)

array([[534, 277],
       [758, 831]], dtype=int64)

In [248]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.56875


In [249]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

GENSIM

In [250]:
words =[]
for sent in df['reviewText']:
    sent_token = sent_tokenize(sent)
    # froom aa parangraph firstly getting sentances 
    for word in sent_token:
        ## this second method can also be used to preprocess where in we can paass the sentence tokens to simple_preprocess 
        words.append(simple_preprocess(word))

In [251]:
import gensim
model = gensim.models.Word2Vec(words)

In [252]:
model.epochs

5

In [253]:
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis = 0)

In [254]:
from tqdm import tqdm

In [255]:
X = []
for i in tqdm(range(0,len(words))):
    X.append(avg_word2vec(words[i]))

100%|██████████| 12000/12000 [00:16<00:00, 732.24it/s]


In [256]:
len(X)

12000

In [257]:
len(df)

12000

In [258]:
X[0].reshape(1,-1).shape

(1, 100)

In [259]:
dfs  = []
for i in range (0,len(X)):
    df1 = pd.DataFrame(X[i].reshape(1,-1))
    dfs.append(df1)

In [260]:
df1 = pd.concat(dfs, ignore_index=True)

In [261]:
X =df1

In [263]:
y = df['rating']

In [264]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state =42)

In [265]:
from sklearn.naive_bayes import GaussianNB
nb_model_gen=GaussianNB().fit(X_train,y_train)

In [266]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [267]:
y_pred_gen =nb_model_gen.predict(X_test)

In [268]:
print("gensim  ",accuracy_score(y_test,y_pred_gen))

gensim   0.70125


In [269]:
confusion_matrix(y_test,y_pred_gen)

array([[ 579,  224],
       [ 493, 1104]], dtype=int64)